### PR TITLE
Update forge modules

### PR DESCRIPTION
**Pull request by adrianjgeorge**
Update versions so that new capabilities can be leveraged

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
I did some cursory testing of this in vagrant. Puppet librarian can resolve all the versions without problem.

**Comment by Mario-Lopez** [comment]
Is it worth updating the IntelliJ version since you're in here?

**Comment by adrianjgeorge** [comment]
i suppose i could

**Comment by adrianjgeorge** [comment]
done

**Pull request merged**
